<?php

namespace Source\Employees;

class Saller extends Employee
{
    private $sallesValue;

    public function __construct($name, $workhours, $valuehours, $sallesValue)
    {
        parent::__construct($name, $workhours, $valuehours);
        $this->sallesValue = $sallesValue;
    }

    public function salaryCalc(): void
    {
        parent::salaryCalc(); // TODO: Change the autogenerated stub
        $this->salary = $this->salary + ($this->sallesValue * 0.10);
    }
}